### ISSUE TITLE
issue with telegram token envirement variable

### ISSUE THREAD

**Issue by squishfunk** [marce1l/snipers#1]
hello

im trying to cargo run but i recived this kind of error:

```
Failed to retrieve 'me': Api(Unknown("Not Found"))
```
But my token is valid and shoud be work

**Comment by marce1l** [comment]
Hey,

Where did you set the teloxide token environment variable in?
Currently the app expects it to be set in the main.rs file, and it overwrites your environment variable if it was set before the execution of main.rs and you left those lines empty.
https://github.com/marce1l/snipers/blob/970746861cddda341e30a8d1b78ba77841a76836/src/main.rs#L22-L30

This is a dumb design by me. I will remove this part and make it so you can for example use a .env file instead. Meanwhile you can try setting the environment variable in the main.rs file.
